<a href="https://colab.research.google.com/github/Marie121899/121899/blob/main/Copy_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Regression

Step1. Import packages and classes

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression


variables"
1. Independent
2. Dependent

In [ ]:
x = np.array([25,35,45,55,65,75])
y =  np.array([5,20,14,32,22,38])

In [ ]:
print(x)
print(y)

[25 35 45 55 65 75]
[ 5 20 14 32 22 38]


In [ ]:
# Reshape x array because it's required to be two dimensional, or to be more precise

x = x.reshape((-1,1))

In [ ]:
print(x)
x.shape

[[25]
 [35]
 [45]
 [55]
 [65]
 [75]]


(6, 1)

Create a model nad fit it

In [ ]:
model = LinearRegression()

In [ ]:
#Train our model
model.fit(x,y)


LinearRegression()

Once you have your model fittede, you can det the results to check weither the model works satisfactorily and interpret it

In [ ]:
r_sq_score =  model.score(x,y)
print('Coefficient of determination (How accurate is the model): ', r_sq_score)

Coefficient of determination (How accurate is the model):  0.7158756137479542


In [ ]:
print('Intercept: ', model.intercept_)

Intercept:  -5.166666666666668


In [ ]:
print('Scope (m):', model.coef_)

Scope (m): [0.54]


In [ ]:
y_pred =  model.predict(x)

In [ ]:
print("Actual values", y)
print("Predicted Response:", y_pred)

Actual values [ 5 20 14 32 22 38]
Predicted Response: [ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


### Multiple Linear Regression

Step One:
Import packages and classes

In [ ]:
u = [[10,21],[5,18], [15,24], [25,56], [35,11], [55,15],[55,34],[50,35]]
v = [4,14,15,20,14,32,22,38]

In [ ]:
print(u)
print(v)

[[10, 21], [5, 18], [15, 24], [25, 56], [35, 11], [55, 15], [55, 34], [50, 35]]
[4, 14, 15, 20, 14, 32, 22, 38]


In [ ]:
u, v = np.array(u), np.array(v)

In [ ]:
print(u)
print(v)

[[10 21]
 [ 5 18]
 [15 24]
 [25 56]
 [35 11]
 [55 15]
 [55 34]
 [50 35]]
[ 4 14 15 20 14 32 22 38]


Create a model Fit

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(u, v)

LinearRegression()

In [ ]:
r_square = model.score(u,v)
print('Coefficient of determination: ', r_square)


Coefficient of determination:  0.6505022021743412


In [ ]:
print('Intercept:' , model.intercept_)




Intercept: 3.637429515508039


In [ ]:
print('Slope: ', model.coef_)

Slope:  [0.40849937 0.12979309]


Predict Response

In [ ]:
v_pred = model.predict(u)

print('Predicted response: ', v_pred)
print('Actual Values of v', v)

Predicted response:  [10.44807812  8.016202   12.87995424 21.11832684 19.36263146 28.05179122
 30.51785994 28.60515618]
Actual Values of v [ 4 14 15 20 14 32 22 38]
